# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build + TestFlight (CI: Match ile imza)"
  lane :custom_lane do
    match(type: "appstore", readonly: true)
    build_app(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      configuration: "Release",
      derived_data_path: "build/ios",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.dahis.app" => "match AppStore com.dahis.app"
        }
      }
    )
    upload_to_testflight
  end
end
